name = "x5-webrtc-signaling"
main = "src/index.ts"
compatibility_date = "2026-04-29"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "RoomObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomObject"]

